container:
  image: golang:latest

env:
  GOPROXY: https://proxy.golang.org

task:
  name: Release Binaries (Dry Run)
  only_if: $CIRRUS_TAG == ''
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  install_script: brew update && brew install go goreleaser
  release_script: goreleaser build --snapshot
  binaries_artifacts:
    path: "dist/agent_*/agent*"

task:
  name: Release Binaries
  only_if: $CIRRUS_TAG != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
    SENTRY_ORG: cirrus-labs
    SENTRY_PROJECT: persistent-workers
    SENTRY_AUTH_TOKEN: ENCRYPTED[!c16a5cf7da5f856b4bc2f21fe8cb7aa2a6c981f851c094ed4d3025fd02ea59a58a86cee8b193a69a1fc20fa217e56ac3!]
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  install_script: brew update && brew install go goreleaser getsentry/tools/sentry-cli
  release_script: goreleaser
  create_sentry_release_script:
    - export SENTRY_RELEASE="cirrus-ci-agent@$CIRRUS_TAG"
    - sentry-cli releases new $SENTRY_RELEASE
    - sentry-cli releases set-commits $SENTRY_RELEASE --auto
    - sentry-cli releases finalize $SENTRY_RELEASE
